### ISSUE TITLE
Create a dropdown user menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#269]
The previous eventyay version had a personal dropdown menu. Recreate a simple menu using this idea with the following menu items:
* My Orders
* Account
* Organiser Area (Only show this if the account is also an organiser)
* Logout
Remove the logout button next to the name.

![Screenshot from 2024-07-31 16-11-57](https://github.com/user-attachments/assets/e5b216dd-f01c-4099-8f4c-fbd64c12cdc8)
![Screenshot from 2024-07-31 16-09-30](https://github.com/user-attachments/assets/0fdb4446-1f1f-4e39-968c-ceab11766830)

**Comment by odkhang** [comment]
Hi @mariobehling,

about item 'Organiser Area (Only show this if the account is also an organiser)'
Because customer account and organiser account is in different model, we cannot check it, so there're 2 options:
1. 'Organiser Area' will be showed in dropdown menu, when user click and go into org area, will require login to organizer area
2. remove 'Organiser Area' item

Please let me know your idea

**Comment by mariobehling** [comment]
Remove "Organiser Area" for now.

**Comment by mariobehling** [comment]
Languages and name are no longer in the same line and dropdown menu is empty.

![Screenshot from 2024-08-14 16-11-31](https://github.com/user-attachments/assets/7ea13c49-5542-4baa-a7a2-6cb12acea3c1)

**Comment by odkhang** [comment]
Hi @mariobehling, please help me to check again

For existing event, for any changes relate to css (which this PR about) , we must go to setting -> shop design -> save it to make function regenerate_css to re-run -> then new css will be applied.
I did it for wikimania event, it look fine now, please help me to test it 

![image](https://github.com/user-attachments/assets/b88f9a3d-c4b3-4369-9545-c5a433f8636c)

**Comment by mariobehling** [comment]
This issue still persists. Reproduce by creating a new account without tickets.
