### ISSUE TITLE
Implement organizer onboarding process

### ISSUE THREAD

**Issue by mariobehling** [fossasia/eventyay-tickets#379]
Currently there is no process to onboard organisers. Add an onboarding page at /signup

Also implement linked basic pages with heading at 
/pricing
/privacy
/terms

Find the onboarding form below.

---

**Welcome! Get started with our platform and explore—no strings attached.**  
Feel free to create your event and try out our software at no cost, with no commitments. We’ll only charge you when you’re ready to make your ticket shop public, and we’ll go over the billing process with you beforehand. You can find all the pricing details [here].

---

**Nice to meet you! Let’s get to know each other.**  

**What’s your name?**  
[*John Doe*]  
Use your personal name rather than your company’s—you can invite your team later and give them access.

**What’s your email address?**  
[*doe@example.org*]  
This will be your login, and we’ll use it to reach out if needed.

**Create a password**  
[*••••••*]

**Confirm your password**  
[*••••••*]

---

**Whose events will you be managing?**  

**Organizer name**  
[*Company name, association, institution, ...*]

**Shortened address**  
[*https://app.eventyay.com/[short form]*]  
This will be the link where your events are hosted. It will also act as a shorthand for your account. If you’d like to use a custom domain, you can set that up after registration.

---

**Agreement to Policies**  
☑ I have read and agree with the privacy policy.  
☑ I have read and agree with the terms of service.  
*Please note: Our services are only available to businesses and registered entities, not to individual consumers.*

**Comment by odkhang** [comment]
Hi @mariobehling,
So basically we will have 3 pages in the header of https://app-test.eventyay.com/tickets/control/register
The first form as I understand, when user click to "Pricing" in the header of signup page, system will redirect them to pricing page

> Welcome! Get started with our platform and explore—no strings attached.
Feel free to create your event and try out our software at no cost, with no commitments. We’ll only charge you when you’re ready to make your ticket shop public, and we’ll go over the billing process with you beforehand. You can find all the pricing details [here].

Next 3 forms:
- The first one: it will replace the current register form, right?

![image](https://github.com/user-attachments/assets/e14e0842-1b59-4ff4-9b79-7bfcefbcefbe)


- second form look like you want to allow User create organizer during register, is it correct? for your information, currently only Admin can create organizer -> So if you want allow new User create organizer, I will update the permission of ticket system allow normal User to create organizer.

- last one just a argeement, we will put it in the bottom of User register form.

what about /privacy and /terms pages? what will we show of that 2 pages?

**Comment by mariobehling** [comment]
Thank you for your input. We definitely need the pages privacy and terms. They should be editable from the admin section of eventyay-common. In regards to the sign up I am having second thoughts. Because we can also leave the current sign up method and allow normal accounts to create an organiser.

These organisers can then create events, but they can only make the events public if they add a credit card.

I think this would be an easier onboarding process. 

Does this work?

**Comment by odkhang** [comment]
Hi @mariobehling,
1. First about the privacy and terms, yes, we can implement a settings page in eventyay-common, allow Admin to input the text which will be shown in /privacy and /terms page.
2. As currently, a new User has no permission on control pages until they were added into a Organizer (into a Team with corresponding permission), then they can create/update event within that Organizer.
 - As you mention, we will keep the current signup page, and if they go to Organizer page, they will able to create a Organizer by themselves, and of course they will own that Organizer and able to create Event under that Organizer.
 - We will add new field in Organizer settings for credit card input (which will be used to check if they want to public Event)
 - In Event settings, in order to make Event public, we will have additional check which is if credit card is added at Organizer settings.
Is it all correct with what you want in this issue?
And since credit card is sensitive information, should we ask User for that info? and how should we manage it? encrypt it or what is your suggestion?

**Comment by odkhang** [comment]
I just take a look back to this issue https://github.com/fossasia/eventyay-tickets/issues/380
so credit card you mentioned is this field in Billing setting in Organizer setting:
```
Payment Information
Please enter your credit card details for monthly fee payments.
```
So there's till a open point that how can we manage credit card info at our system.

**Comment by mariobehling** [comment]
Use Stripe for credit card storage: https://docs.stripe.com/terminal/features/saving-cards/overview

**Comment by odkhang** [comment]
As discussed, If an Organizer has unpaid invoice, we will prevent them to public or re-public Event.

**Comment by mariobehling** [comment]
Thank you for following up. Reviewing the options I think we can simplify the page creation even further following the pages module for event organisers.

1. The URL structure

Expected would be, e.g. https://app-test.eventyay.com/tickets/pricing/

2. Provide a simple page creation process following the example of the page module used for events and provide the following options:
* Page title
* Custom URL, e.g. /faq (also provide this for all languages)
* Show link on the website start page [tick box]
* Show in header menu on all pages [tick box]
* Show in website footer menu on all pages [tick box] (The website footer should be below the event footer)
* Require the user to acknowledge this page before the sign up is created (e.g. for terms of service).
* Text box 

3. Ensure all items show up in the normal user interface. Currently there is no drop-down menu or anything like that.

![Screenshot from 2024-11-21 22-30-00](https://github.com/user-attachments/assets/94efb3ba-c9c7-41d6-8764-4b9cd3073a87)

**Comment by odkhang** [comment]
Hi @mariobehling, please help me to confirm and give feedback with below point:
1. Custom URL, e.g. /faq (also provide this for all languages)
=> I'm not sure what you mean when mentioned "also provide this for all languages", you mean different URL for different languages? because currently, display language of eventyay-tickets is set in cookie, which mean User can change to different language as they want, similar in ticket shop => we need to implement a languages bar as well in view content page
![image](https://github.com/user-attachments/assets/07ae0555-6f2f-48c4-98e6-de9e2eb43e85)

2. Show link on the website start page [tick box]
=> If box is checked, page will be showed like below, is it okay? (I think it should be started with some text "Please read below links for more information: Pricing, Terms, Privacy")
![image](https://github.com/user-attachments/assets/3cf18ff6-1aba-4348-b571-cc52f2e6b799)

3. Show in header menu on all pages [tick box]
![image](https://github.com/user-attachments/assets/e7991133-b065-48b1-9c35-faec2fc1dd63)

4. Show in website footer menu on all pages [tick box] (The website footer should be below the event footer)
![image](https://github.com/user-attachments/assets/360c387f-225a-4423-8dd7-3d420180e371)

5.Require the user to acknowledge this page before the sign up is created (e.g. for terms of service).
![image](https://github.com/user-attachments/assets/3bd5fe50-303b-42cc-a872-b62b625c72fc)

Please share your thought about this.

**Comment by mariobehling** [comment]
@odkhang Thank you! In regards to 1 and 2, please do not do it yet as you are correct it would require more changes. We also dont have a real start page yet. We will do that in another issue first.
